 #1
# n=int(input("enter the rows"))
# for i in range(0,n):
#     for j in range(i+1):
#         print("*",end='')
#     print()

#2
# n=int(input("enter the rows"))
# for i in range(n):
#     for j in range(i+1):#or print(str(i+1)+'')*(i+1)
#         print(i+1,end='')
#     print()    
# n=int(input("enter the rows"))            
# for i in range(n):
#     for j in range(i+1):
#         print(chr(65+i),end=' ')
#     print()    

# n=int(input("enter the rows"))
# for i in range(n):
#     for j in range(i+1):
#         print(j+1,end='')
#     print()    

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(i+1):
#         print(chr(65+j), end=' ')
#     print()    

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(i+1):
#         print(n-j,end=' ')
#     print()    

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(i+1):
#         print(chr(64+n-j),end=' ')
#     print()    

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print("*",end=' ')
#     print()    


# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print(i+1,end=' ')
#     print()  

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print(chr(65+i),end=' ')
#     print()    


# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print(n-i,end=' ')
#     print()    

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print(chr(64+n-i),end=' ')
#     print()    
  

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print(j+1,end=' ')
#     print()    

# n=int(input("enter the rows "))
# for i in range(n):
#     for j in range(n-i):
#         print(chr(65+j),end=' ')
#     print()   
# 
#
# n=int(input("enter the rows "))
# for i in range(n):
#    print(' '*(n-i-1)+'* '*(i+1))
#    print()

# n=int(input("enter the rows "))
# for i in range(n):
#     print(' '*(n-i-1)+ (str(i+1)+' ')*(i+1))
#     print()   
#    1

#    2 2

#   3 3 3

#  4 4 4 4

# 5 5 5 5 5

# n=int(input("enter the rows "))
# for i in range(n):
#     print(' '*(n-i-1)+ (chr(65+i)+' ')*(i+1))

# n=int(input("enter the row ="))
# for i in range(n):
#     print((' '*(n-i-1)),end=' ')
#     for j in range(i+1):
#         print(j+1,end=' ')
#     print()




